#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: GPL-2.0-only
#

additional_commands:
  add_sources:
    kwargs:
      ASMFILES: '*'
      CFILES: '*'
      DEP: '*'
      PREFIX: '*'
  config_option:
    kwargs:
      DEFAULT: '*'
      DEFAULT_DISABLED: '*'
      DEPENDS: '*'
  config_string:
    flags:
    - UNQUOTE
    - UNDEF_DISABLED
    kwargs:
      DEFAULT: '*'
      DEPENDS: '*'
  cppfile:
    kwargs:
      EXACT_NAME: '*'
      EXTRA_DEPS: '*'
      EXTRA_FLAGS: '*'
  gen_invocation_header:
    flags:
    - ARCH
    - SEL4ARCH
    - LIBSEL4
    kwargs:
      OUTPUT: '*'
      XML: '*'
  register_driver:
    kwargs:
      CFILES: '*'
      PREFIX: '*'
  find_in_map:
    kwargs:
      RESULT_VAR: '1'
      KEY_VAR: '1'
      DEFAULT: '1'
      MAP: '1+'
  declare_default_headers:
    kwargs:
        TIMER_FREQUENCY: '*'
        MAX_IRQ: '*'
        NUM_PPI: '*'
        INTERRUPT_CONTROLLER: '*'
        TIMER: '*'
        KERNEL_WCET: '*'
        CLK_MAGIC: '*'
        CLK_SHIFT: '*'
        TIMER_PRECISION: '*'
        TIMER_OVERHEAD_TICKS: '*'
        SMMU: '*'
        MAX_SID: '*'
        MAX_CB: '*'
  declare_platform:
    flags:
    - NO_DEFAULT_DTS
    kwargs:
        NAME: '*'
        ARCH: '*'
        CAMKE_VAR: '*'
        MACH: '*'
        C_DEFINE: '*'
        FLAGS: '*'
        SOURCES: '*'
        BOARDS: '*'
