#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: GPL-2.0-only
#

additional_commands:
  cppfile:
    pargs:
      nargs: 3
    kwargs:
      EXTRA_DEPS: '*'
      EXTRA_FLAGS: '*'
  add_sources:
    kwargs:
      ASMFILES: '*'
      CFILES: '*'
      DEP: '*'
      PREFIX: '*'
  config_option:
    flags:
    - UNQUOTE
    kwargs:
      DEFAULT: '*'
      DEFAULT_DISABLED: '*'
      DEPENDS: '*'
  config_string:
    flags:
    - UNQUOTE
    kwargs:
      DEFAULT: '*'
      DEPENDS: '*'
  cpp_file:
    kwargs:
      EXACT_NAME: '*'
      EXTRA_DEPS: '*'
      EXTRA_FLAGS: '*'
  gen_invocation_header:
    flags:
    - ARCH
    - SEL4ARCH
    - LIBSEL4
    kwargs:
      OUTPUT: '*'
      XML: '*'
  register_driver:
    kwargs:
      CFILES: '*'
      PREFIX: '*'
  declare_default_headers:
    kwargs:
        TIMER_FREQUENCY: 1
        MAX_IRQ: 1
        NUM_PPI: 1
        INTERRUPT_CONTROLLER: 1
        TIMER: 1
        KERNEL_WCET: 1
        CLK_MAGIC: 1
        CLK_SHIFT: 1
        TIMER_PRECISION: 1
        TIMER_OVERHEAD_TICKS: 1
        SMMU: 1
        MAX_SID: 1
        MAX_CB: 1
