# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Compilation actions to run on pull requests

name: Compile

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  standalone_kernel:
    name: kernel
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, AARCH64, RISCV32, RISCV64, IA32, X64]
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v4
    - uses: axel-h/ci-actions/standalone-kernel@patch-axel-6
      with:
        ARCH: ${{ matrix.arch }}
        COMPILER: ${{ matrix.compiler }}
