# Copyright 2024, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# hardware builds and runs
#
# See sel4test-hw/builds.yml and sel4bench-hw/builds.yml in the repo
# seL4/ci-actions for configs.

name: HW

on:
  # needs PR target for secrets access; guard by requiring label
  pull_request_target:
    types: [synchronize, labeled]

jobs:
  sel4-projects:
    uses: axel-h/ci-actions/.github/workflows/sel4projects.yml@patch-axel-7
    secrets: inherit
