# Copyright 2021 Proofcraft Pty Ltd
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

# To reduce the load we cancel any older runs of this workflow for the current
# PR. Such runs exist, if there were new pushes to the PR's branch without
# waiting for the workflow to finish. As a side effect, pushing new commits now
# becomes a convenient way to cancel all the older runs, e.g. if they are stuck
# and would only be stopped by the timeout eventually.
concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/.github/workflows/pr.yml@patch-axel-7

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/git-diff-check@patch-axel-7

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/bashisms@patch-axel-7

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/style@patch-axel-7

  preprocess:
    name: Preprocess
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, AARCH64, RISCV64, X64]
        feature: ["", MCS]
        exclude:
          - arch: ARM_HYP
            feature: MCS
          - arch: AARCH64
            feature: MCS
          - arch: X64
            feature: MCS
    steps:
    - uses: axel-h/ci-actions/preprocess@patch-axel-7
      with:
        L4V_ARCH: ${{ matrix.arch }}
        L4V_FEATURES: ${{ matrix.feature }}

  cproof:
    name: C Proofs
    runs-on: ubuntu-latest
    # Run if
    # - one of the labels is added
    # - a (re-)open/push happened and the label was present.
    # Do not run when other labels are added.
    if: ${{ (github.repository_owner == 'seL4') &&
            ((github.event.action != 'labeled') &&
             contains(github.event.pull_request.labels.*.name, 'proof-test')) ||
            ((github.event.action == 'labeled') &&
             (github.event.label.name == 'proof-test')) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: ARM
            session: CRefine SimplExportAndRefine
          - arch: ARM_HYP
            session: CRefine
          - arch: RISCV64
            session: CRefine SimplExportAndRefine
          - arch: X64
            session: CRefine
          - arch: AARCH64
            session: CRefine
          - arch: RISCV64
            features: MCS
            session: CRefine
    # test only most recent push to PR:
    concurrency: seL4-PR-C-proofs-pr-${{ github.event.number }}-idx-${{ strategy.job-index }}
    steps:
    - name: Proofs
      uses: axel-h/ci-actions/aws-proofs@patch-axel-7
      with:
        L4V_ARCH: ${{ matrix.arch }}
        L4V_FEATURES: ${{ matrix.features }}
        isa_branch: ts-2023
        session: ${{ matrix.session }}
        manifest: ${{ matrix.features == 'MCS' && 'mcs.xml' || 'default.xml' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    - name: Upload kernel builds
      uses: actions/upload-artifact@v4
      with:
        name: kernel-builds-${{ matrix.arch }}-${{ matrix.features }}
        path: artifacts/kernel-builds
        if-no-files-found: ignore
    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.arch }}-${{ matrix.features }}
        path: logs.tar.xz
