# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request, workflow_dispatch]

jobs:
  pr-checks:
    name: Checks
    uses: axel-h/ci-actions/.github/workflows/pr.yml@patch-axel-7
