# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/.github/workflows/pr.yml@patch-axel-17

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/git-diff-check@patch-axel-17

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/bashisms@patch-axel-17

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: axel-h/ci-actions/style@patch-axel-17

  preprocess:
    name: Preprocess
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, AARCH64, RISCV64, X64]
        feature: ["", MCS]
        exclude:
          - arch: ARM_HYP
            feature: MCS
          - arch: AARCH64
            feature: MCS
          - arch: X64
            feature: MCS
    steps:
    - uses: axel-h/ci-actions/preprocess@patch-axel-17
      with:
        L4V_ARCH: ${{ matrix.arch }}
        L4V_FEATURES: ${{ matrix.feature }}
