# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test simulation runs
#
# See sel4test-sim/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test Sim

on:
  pull_request:
    paths-ignore:
      - 'manual/**'
      - 'LICENSES/**'
      - '*.md'

jobs:
  sim:
    name: Simulation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [armv7a]
        compiler: [gcc]
    steps:
    - uses: axel-h/ci-actions/sel4test-sim@pr-54
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
