# Copyright 2024, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# hardware builds and runs
#
# See sel4test-hw/builds.yml and sel4bench-hw/builds.yml in the repo
# seL4/ci-actions for configs.

name: HW

on:
  # needs PR target for secrets access; guard by requiring label
  pull_request_target:
    types: [synchronize, labeled]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - env:
        github_JSON: ${{ toJSON(github) }}
      run: |
        echo github.workspace = ${{ github.workspace }}
        echo GITHUB_WORKSPACE = ${GITHUB_WORKSPACE}
        echo github.event_name = ${{ github.event_name }}
        echo github.event.action = ${{ github.event.action }}
        echo labeled: ${{ contains(fromJSON('["hw-build", "hw-test"]'), github.event.label.name) }}
        echo hw-build: ${{ contains(github.event.pull_request.labels.*.name, 'hw-build') }}
        echo hw-test: ${{ contains(github.event.pull_request.labels.*.name, 'hw-test') }}
        echo hw-bench: ${{ contains(github.event.pull_request.labels.*.name, 'hw-bench') }}

  sel4-projects:
    uses: axel-h/ci-actions/.github/workflows/sel4projects.yml@patch-axel-7
    with:
        projects: sim, sel4test, sel4bench
    secrets: inherit
