# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test hardware builds and runs
#
# See sel4test-hw/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test HW

on:
  # needs PR target for secrets access; guard by requiring label
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

# downgrade permissions to read-only as you would have in a standard PR action
permissions:
  contents: read

jobs:
  create_hw_build_matrix:
    name: HW Build Matrix
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' ||
            github.event_name == 'pull_request_target' &&
              github.event.action != 'labeled' &&
              (contains(github.event.pull_request.labels.*.name, 'hw-build') ||
               contains(github.event.pull_request.labels.*.name, 'hw-test')) ||
            github.event_name == 'pull_request_target' &&
              github.event.action == 'labeled' &&
              (github.event.label.name == 'hw-build' ||
               github.event.label.name == 'hw-test') }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - id: matrix
      uses: axel-h/ci-actions/sel4test-hw-matrix@patch-axel-1
      with:
          action_param: --matrix-build

  hw-build:
    name: HW Build
    needs: create_hw_build_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.create_hw_build_matrix.outputs.matrix) }}
    steps:
    - name: Build
      uses: axel-h/ci-actions/sel4test-hw@patch-axel-1
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
        sha: ${{ github.event.pull_request.head.sha }}
    - name: Upload images
      uses: actions/upload-artifact@v3
      with:
        name: images-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-images.tar.gz'
    - name: Upload kernel.elf files
      uses: actions/upload-artifact@v3
      with:
        name: kernel.elf-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-kernel.elf'

  create_hw_test_matrix:
    name: HW Test Matrix
    needs: hw-build
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'seL4' &&
            (github.event_name == 'push' ||
             github.event_name == 'pull_request_target' &&
               github.event.action != 'labeled' &&
               contains(github.event.pull_request.labels.*.name, 'hw-test') ||
             github.event_name == 'pull_request_target' &&
               github.event.action == 'labeled' &&
               github.event.label.name == 'hw-test') }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - id: matrix
      uses: axel-h/ci-actions/sel4test-hw-matrix@patch-axel-1
      with:
          action_param: --matrix-test

  hw-run:
    name: HW Run
    runs-on: ubuntu-latest
    needs: create_hw_test_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.create_hw_test_matrix.outputs.matrix) }}
    steps:
      - name: Get machine queue
        uses: actions/checkout@v3
        with:
          repository: seL4/machine_queue
          path: machine_queue
          token: ${{ secrets.PRIV_REPO_TOKEN }}
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: images-${{ matrix.march }}-${{ matrix.compiler }}
      - name: Run
        uses: axel-h/ci-actions/sel4test-hw-run@patch-axel-1
        with:
          platform: ${{ matrix.platform }}
          compiler: ${{ matrix.compiler }}
          mode: ${{ matrix.mode }}
          index: $${{ strategy.job-index }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
