# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test hardware builds and runs
#
# See sel4test-hw/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test-HW

on:
  # needs PR target for secrets access; guard by requiring label
  pull_request_target:
    # For all events the property "github.event.pull_request" holds the details
    # of the PR.
    types:
    - opened
    - reopened
    - synchronize  # push on PR's branch
    - labeled  # label added to PR (there is "unlabled" also)

# downgrade permissions to read-only as you would have in a standard PR action
permissions:
  contents: read

# To reduce the load (especiually on the machine queue) we cancel any older runs
# of this workflow for the current PR. Such runs exist, if there were new pushes
# to the PR's branch without waiting for the workflow to finish. As a side
# effect, pushing new commits now becomes a convenient way to cancel all the
# older runs, e.g. if they are stuck and would only be stopped by the timeout
# eventually.
# Note that we could do the concurrency handling at a finer level, and only wrap
# the actual run on the hardware. But there seems not much gain in letting the
# older builds run, as these are usually obsolete with new pushes also.
concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  hw-build:
    name: HW Build
    runs-on: ubuntu-latest
    # Run if
    # - one of the labels is added
    # - a (re-)open/push happened and one of the labels was present.
    # Do not run when other labels are added.
    if: ${{ ((github.event.action != 'labeled') &&
             (contains(github.event.pull_request.labels.*.name, 'hw-build') ||
              contains(github.event.pull_request.labels.*.name, 'hw-test'))) ||
            ((github.event.action == 'labeled') &&
             ((github.event.label.name == 'hw-build') ||
              (github.event.label.name == 'hw-test'))) }}
    strategy:
      fail-fast: false
      matrix:
        # There is no "rv32imac" hardware yet.
        march: [armv7a, armv8a, nehalem, rv64imac]
        compiler: [gcc, clang]
    steps:
    - name: Build
      uses: seL4/ci-actions/sel4test-hw@master
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
        sha: ${{ github.event.pull_request.head.sha }}
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-images.tar.gz'
    - name: Upload kernel.elf files
      uses: actions/upload-artifact@v4
      with:
        name: kernel.elf-${{ matrix.march }}-${{ matrix.compiler }}
        path: '*-kernel.elf'

  the_matrix:
    name: Matrix
    needs: hw-build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - id: matrix
      uses: seL4/ci-actions/sel4test-hw-matrix@master

  hw-run:
    name: HW Run
    runs-on: ubuntu-latest
    needs: the_matrix
    # The checks at the dependent step "hw-build" already filtered a lot, so we
    # can use a much simpler check here. Run this step only if the 'hw-test' is
    # present (the labeling event has also added it). Do not run on forks,
    # because they can't access the hardware test farm.
    if: ${{ (github.repository_owner == 'seL4') &&
             contains(github.event.pull_request.labels.*.name, 'hw-test') }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.the_matrix.outputs.matrix) }}
    steps:
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: images-${{ matrix.march }}-${{ matrix.compiler }}
      - name: Run
        uses: seL4/ci-actions/sel4test-hw-run@master
        with:
          platform: ${{ matrix.platform }}
          compiler: ${{ matrix.compiler }}
          mode: ${{ matrix.mode }}
          index: $${{ strategy.job-index }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
