# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# xmllint for seL4 IDL files

name: XML

on:
  push:
    branches:
      - master
    paths:
      - 'libsel4/**/sel4*.xml'
      - 'libsel4/**/sel4*.xsd'
      - 'libsel4/include/api/syscall.xml'
      - 'libsel4/include/api/syscall.xsd'
  pull_request:
    paths:
      - 'libsel4/**/sel4*.xml'
      - 'libsel4/**/sel4*.xsd'
      - 'libsel4/include/api/syscall.xml'
      - 'libsel4/include/api/syscall.xsd'

# To reduce the load we cancel any older runs of this workflow for the current
# PR. Such runs exist, if there were new pushes to the PR's branch without
# waiting for the workflow to finish. As a side effect, pushing new commits now
# becomes a convenient way to cancel all the older runs, e.g. if they are stuck
# and would only be stopped by the timeout eventually.
# For deployment to the master branch, the workflow will run on each push, no
# skipping or cancellation will happen. This works, becuase the concurrency
# group uses "github.run_id", which is a unique number for every workflow run
# within the whole repository.
# Note that "${{ <cond> && <ret_true> || <ret_false> }}" is the designated
# github expression to emulate a ternary operator, where <ret_true> must be
# something that does not evaluate to 'false' so <ret_false> is returned always.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'pull_request' && github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  xmllint:
    name: XML Lint
    runs-on: ubuntu-latest
    steps:
    - name: apt-get update
      run: sudo apt-get update
    - name: install xmllint
      run: sudo apt-get install libxml2-utils
    - uses: actions/checkout@v4
    - name: run xmllint
      run: |
        find libsel4 -name "sel4*.xml" | \
        xargs xmllint --schema libsel4/tools/sel4_idl.xsd --noout
        xmllint --schema libsel4/include/api/syscall.xsd --noout libsel4/include/api/syscall.xml
